### ISSUE TITLE
guide pls

### ISSUE THREAD

**Issue by realrj** [andreiapostoae/dota2-predictor#1]
pls help how to use this there are error comming unknown mmr etc etc

**Comment by andreiapostoae** [comment]
Hello and thank you for your interest! 

The work is still in progress for this project, as there have been some bugs in evaluating the model that need fixing. When these issues are fixed, I will post a release with a README of how to train and query the model. If you want to be informed when the release is made (hopefully very soon), you can star the project to see its updates.

Have a nice day,
Apo
