### ISSUE TITLE
tkinter crashing on startup NSInvalidArgumentException

### ISSUE THREAD

**Issue by flyingbanana1024102** [andreiapostoae/dota2-predictor#8]
Running the code as is without Anaconda crashes python on startup with a `NSInvalidArgumentException`.

Adding these two lines from this answer to the top of the `basic_gui.py` file solves this problem.

[Python crashes after Tkinter and matplotlib.pyplot are imported](https://stackoverflow.com/a/42086218/2456722)

**Comment by andreiapostoae** [comment]
I updated the file where I import matplotlib. However, I find the issue odd as theoretically tkinter and matplotlib should not interact. Could you please check if it works now as I do not have a macOS device?

**Comment by andreiapostoae** [comment]
Tkinter GUI will be removed and a web app will take its place. This way people will not have compatibility problems afterwards.
