### ISSUE TITLE
Error: Please set API_KEY environment variable.

### ISSUE THREAD

**Issue by CharlesLiuyx** [andreiapostoae/dota2-predictor#9]
Hi! Amazing project!!

When I try to run `steam_miner.py`, it returned the error `Please set API_KEY environment variable.`

How could I solve this problem 

os: Window10 64bits 
envi: Anaconda python 2.7

**Comment by CharlesLiuyx** [comment]
I try to add one line: os.environ['API_KEY'] = 'MyKey' to solve it then I meet an new error `KeyError: 'matches'`

**Comment by CharlesLiuyx** [comment]
I have solved it! Thanks~

**Comment by andreiapostoae** [comment]
What was the problem? Glad you figured it out!

**Comment by CharlesLiuyx** [comment]
At the begining there is the API KEY problem so I add my SteamAPI Key. Problem done!
The `Key:Error` related to json format  because I confused by 2 different SteamWeb API.
